import {
  Brain,
  BarChart3,
  LineChart,
  Lightbulb,
  Microscope,
  Database,
  Users,
  Target,
  CheckCircle,
  AlertTriangle,
  TrendingUp,
  Network,
  BookOpen,
  FlaskConical,
  Cpu,
  Globe,
  Puzzle,
  Search,
  Shield,
  Zap,
  FileText,
  type LucideIcon,
} from "lucide-react";

/**
 * Maps the fixed icon vocabulary (must match ICON_KEYS in lib/script.ts) to
 * lucide-react components.
 */
export const ICONS: Record<string, LucideIcon> = {
  brain: Brain,
  "chart-bar": BarChart3,
  "chart-line": LineChart,
  lightbulb: Lightbulb,
  microscope: Microscope,
  database: Database,
  users: Users,
  target: Target,
  "check-circle": CheckCircle,
  "alert-triangle": AlertTriangle,
  "trending-up": TrendingUp,
  network: Network,
  "book-open": BookOpen,
  "flask-conical": FlaskConical,
  cpu: Cpu,
  globe: Globe,
  puzzle: Puzzle,
  search: Search,
  shield: Shield,
  zap: Zap,
  "file-text": FileText,
};
